[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed  = 921600

lib_deps =
    miguelbalboa/MFRC522 @ ^1.4.11
    bblanchon/ArduinoJson @ ^7.0.4
    arduino-libraries/NTPClient @ ^3.2.1

build_flags =
    -DCORE_DEBUG_LEVEL=0
