# إعدادات الـ Memory عشان الـ Android Studio يكون أسرع
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# تفعيل الـ AndroidX (ضروري جداً)
android.useAndroidX=true
android.enableJetifier=true

# السطر اللي هيحل المشكلة الحالية (تجاهل توافق SDK 35 مع البلاجن القديم)
android.suppressUnsupportedCompileSdk=35